version: '2'

services:

  applications:
    image: tianon/true
    volumes:
      - ./workspace/php:/var/www

  node:
    build:
      context: ./docker/language/js
    # container_name: nodejs
    # networks:
    #   - frontend
    #   - backend

  nginx:
    build:
      context: ./docker/middleware/nginx
    # container_name: nginx
    volumes:
      - ./docker/middleware/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./workspace/php:/var/www/html
    ports:
      - "80:80"
    # networks:
    #     - frontend
    #     - backend

  mysql:
    build:
      context: ./docker/database/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      # - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ${DATA_SAVE_PATH}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"

### Networks Setup ############################################

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"

volumes:
  mysql:
    driver: "local"