version: '3'

services:
  app:
    build:
      context: ./docker/language/${LANGUAGE}
    volumes:
      - ./workspace/${LANGUAGE}:/var/www/app
    networks:
      app_net:
        ipv4_address: 172.30.0.10

  nginx:
    build:
      context: ./docker/middleware/nginx
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ${NGINX_CONF_PATH}/${LANGUAGE}.conf:/etc/nginx/conf.d/${LANGUAGE}.conf
    networks:
      app_net:
        ipv4_address: 172.30.0.2

  mysql:
    build:
      context: ./docker/database/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DATA_SAVE_PATH}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      app_net:
        ipv4_address: 172.30.0.3

  redis:
    build:
      context: ./docker/middleware/redis
    networks:
      app_net:
        ipv4_address: 172.30.0.4

### Networks Setup ############################################

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24